add_test_executable(test_variable_identifier)
add_test_executable(test_property)
add_test_executable(test_runner)
add_test_executable(test_ssp_parser)
add_test_executable(test_unzipper)
add_test_executable(test_model_instance)
add_test_executable(test_nova_engine)
add_test_executable(test_engine_scheduler)
add_test_executable(test_fixed_step_algorithm)
add_test_executable(test_scenario)
add_test_executable(test_csv_recorder)

if (NOVA_BUILD_CLIB)
    add_test_executable(test_clib)
    target_link_libraries(test_clib PUBLIC libnova_simc)
endif()
